server:
    port: 8081

spring:
    application:
        name: lecturas

    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: jdbc:postgresql://localhost:5432/BD_LIBRO
        username: postgres
        password: Tweet
        driver-class-name: org.postgresql.Driver

    flyway:
        enabled: TRUE
        locations: classpath:db/migration 

logging:
    file:
        name: logs/libro.log
        path: logs
    level:
        root: INFO
        org:
            springframework:
                web: INFO

        rollingpolicy:
            max-file-size: 8MB
            max-history: 30